before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install tidy

install: travis_retry bundle install --without=benchmark

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx
  - ruby-head

notifications:
  email: false
